version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
image: Visual Studio 2019
configuration: Release
before_build:
- cmd: nuget restore
build:
  project: Topshelf.Lamar.sln
  publish_nuget: true
  verbosity: normal
artifacts:
- path: "'*.nupkg'"
deploy:
- provider: NuGet
  api_key:
    secure: UNRGM61q16a8VtMGmRXtnSh+fVvdcLeqQKvoN/FO5yOw36ltVCnfwJykr9bZWj0z
  skip_symbols: true
  artifact: /.*\.nupkg/
notifications:
- provider: Email
  to:
  - habibzaid@gmail.com
  subject: Topshelf.Lamar Build
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true